### ISSUE TITLE
How can i adapt a custom proposal function into AdaptiveMCMC

### ISSUE THREAD

**Issue by marouanehanhasse** [mvihola/AdaptiveMCMC.jl#4]
I want to use this package, i just found it and it looks like everything i need, i have a log target function and the proposal distribution function is customized on this way:
```
using Distributions
nonneg(v) = all(v.>=0) ? true : false

struct OrthoNNDist <: DiscreteMultivariateDistribution
	x0::Vector{Float64}
	oc::Array{Float64,2}
	x1s::Array
	prob::Float64
    #return a new uniform distribution with all vectors in x1s orthogonal to oc
	function OrthoNNDist(x0::Vector{Float64}, oc::Array{Float64,2})
		x1s = []
		for i = 1:size(oc)[2]
			x1 = x0 + oc[:, i]
			if nonneg(x1)
				push!(x1s, x1)
			end
			x1 = x0 - oc[:, i]
			if nonneg(x1)
				push!(x1s, x1)
			end
		end
		new(x0, oc, x1s, 1.0/length(x1s))
	end
end

Base.length(d::OrthoNNDist) = length(d.x0)

Distributions.rand(d::OrthoNNDist) = rand(d.x1s)

Distributions.pdf(d::OrthoNNDist, x::Vector) = x in d.x1s ? d.prob : 0.0
Distributions.pdf(d::OrthoNNDist) = fill(d.prob, size(d.x1s))
Distributions.logpdf(d::OrthoNNDist, x::Vector) = log(pdf(d, x))
```
this proposal function generate arrays, and we can compute the probability from x->y with y being the proposed value, we just need to call `Distributions.pdf(d::OrthoNNDist, x::Vector) ` the same for y->x we can compute their `logpdf` too `Distributions.logpdf(d::OrthoNNDist, x::Vector) ` , and let's suppose the the target function is 
`logtarget(x::Vector)= log(sum(x)/length(x))` and i tried with it before, but i get some method errors, because the proposal should be a function and it shows the mine is type of `OrthoNNDist`, if you want to test this proposal distribution you can use `x0=zeros(8)` and `oc=[0 1 0 0 1 1 0 0 1 0 0 0; 1 0 0 0 1 0 0 0 0 0 0 1; 1 0 1 0 0 0 0 1 0 0 1 0; 0 1 0 0 0 0 1 0 0 0 1 0; 0 0 0 1 0 0 0 1 1 0 0 0; 0 0 0 1 0 0 0 0 0 0 0 1; 0 0 1 0 0 1 0 0 0 1 0 0; 0 0 0 0 0 0 1 0 0 1 0 0]` 
I'd appreciate it if you can show me how can i adapt this proposal function, by a minimal example or anyway.

**Comment by mvihola** [comment]
Thanks for your question.

AdaptiveMCMC.jl is an implementation of two classes of adaptive MCMC algorithms:

* Random-walk proposals
* parallel tempering

There is no functionality to adapt an arbitrary proposal distribution. In fact, adaptation of a generic proposal would be difficult to implement, as adaptation criteria tend to be specific to the type of MCMC...

If you would like to use adaptive parallel tempering, and supply your own proposal distribution, see https://github.com/mvihola/AdaptiveMCMC.jl/issues/3
