### ISSUE TITLE
Suggestion: Support for progress bars?

### ISSUE THREAD

**Issue by astro-kevin** [mvihola/AdaptiveMCMC.jl#7]
Sometimes very long or complex chains take very long time to run. Adding support for a progress bar with eta would help that plan for long runs better.

**Comment by mvihola** [comment]
Thanks, I agree that this could be useful, and it would be straightforward to add (for instance) ProgressMeter.jl. However, I have tried to keep the dependencies minimal. If you know of an elegant way to add support for progress bars without adding a dependency to another package, please let me know!

**Comment by NilsWildt** [comment]
Workaround for everyone interested (also works in Pluto.jl)

    using ProgressLogging
	n_iterapt = 10_000
	L = 2

	
	counter = 0
	id = UUIDs.uuid4()

    function ℓπrwp(x,counter,id) 	
		counter = counter+1
		@logprogress counter/n_iterapt parentid=id

             return yourlikelihood(x)
	end

    adaptive_rwm(x0, x->ℓπrwp(x,counter,id), div(n_iterapt,L); L = L, thin=1)

**Comment by astro-kevin** [comment]
This seems to throw an error 
```
ERROR: LoadError: `@logprogress` must be used inside `@withprogress` or with `_id` keyword argument
```
Is there something missing from the snippet?

**Comment by mvihola** [comment]
I added the ProgressMeter dependency: the new keyword argument `progress` of `adaptive_rwm` controls whether a progress meter is shown. You can also provide a custom one, such as  `progress=Progress(n; dt=3.0)` which updates less frequently...
